// frontend-react/src/layouts/MainHeader/index.jsx
import { React } from "react";
import { useNavigate } from 'react-router-dom';

import { apiService } from '../../shared/api/swagger/swagger.js';

import { Button } from '../../components'

const MainHeader = () => {
    const navigate = useNavigate();

    const logout = () => {
        apiService.logout.Logout();

        navigate('/auth');
        localStorage.removeItem('user')
    };

    return (
        <header>
            <div className="header">
                <h1>TO DO APP (REACT)</h1>
                <Button onClick={logout} classNameOut="header__button">ВЫХОД</Button>
            </div>
        </header>
    )
}

export { MainHeader }

// frontend/src/layouts/MainHeader.vue
<template>
  <v-header>
    <div class="header">
      <h1>TO DO APP 1</h1>
      <Button @click="logout">ВЫХОД</Button>
    </div>
  </v-header>
</template>

<script>
import { Button } from "@/components/UI";

import { apiService } from "../shared/api/swagger/swagger";

export default {
  name: "MainHeader",
  components: {
    Button,
  },
  methods: {
    logout() {
      apiService.logout.Logout();

      this.$router.push({ name: "Authorization" });
    },
  },
};
</script>

<style lang="scss" scoped></style>
