// frontend-react/src/pages/HomePage/index.jsx
import  React, { useState, useEffect } from "react";

import { apiService } from '../../shared/api/swagger/swagger.js';

import { Desk } from "../../components";

const HomePage = () => {
  const statuses = [
    {
      id: 1,
      name: "сделать",
    },
    {
      id: 2,
      name: "в процессе",
    },
    {
      id: 3,
      name: "закончено",
    },
  ];
      
  const [tasks, setTasks] = useState([]);
  const [users, setUsers] = useState([]);

  const updateTasks = tasks => {
    setTasks(tasks)
  }

  useEffect(() => {
    apiService.tasks.Get().then((res) => {
      updateTasks(res.data);
    });

    apiService.users.Get().then((res) => {
       setUsers(res.data)
    });
  }, []);

  return (
    <div className="todo-app">
      {
        statuses && statuses.map((status) => {
            return (
              <Desk
                statusId={status.id}
                statusTitle={status.name}
                tasks={tasks}
                users={users}
                updateTasks={updateTasks}
                key={status.id} />
            );
        })
      }
    </div>
  )
}

export {  HomePage }

// frontend/src/pages/HomePage/index.vue
<template>
  <!--Доски с задачами-->
  <div class="todo-app">
    <!--Компонент Desk, куда передается: 
      categories - массив с названием категории и id
      tasks - массив с названием задач, id и id категории -->
    <Desk
      v-for="status in statuses"
      :key="status.id"
      v-bind:statusId="status.id"
      v-bind:statusTitle="status.name"
      v-bind:tasks="tasks"
      @update:tasks="tasks = $event"
      v-bind:users="users"
    />
  </div>
</template>

<script>
import { apiService } from "../../shared/api/swagger/swagger";

import Desk from "@/components/Desk";

export default {
  name: "HomePage",
  components: {
    Desk,
  },
  data: () => {
    return {
      statuses: [
        {
          id: 1,
          name: "сделать",
        },
        {
          id: 2,
          name: "в процессе",
        },
        {
          id: 3,
          name: "закончено",
        },
      ],
      tasks: [],
      users: [],
    };
  },
  mounted() {
    apiService.tasks.Get().then((res) => {
      this.tasks = res.data;
    });

    apiService.users.Get().then((res) => {
      this.users = res.data;
    });
  },
};
</script>

<style lang="scss" scoped></style>
