// frontend-vue/src/App.vue
<template>
  <v-app>
    <MainHeader v-if="$route.path !== '/auth'" />
    <MainContent />
  </v-app>
</template>

<script>
import { MainHeader, MainContent } from "@/layouts";

export default {
  name: "App",
  components: {
    MainHeader,
    MainContent,
  },
};
</script>

<style lang="scss">
@import "@/assets/scss/main.scss";
</style>

// frontend-react/src/App.jsx
import { React } from "react";
import { useLocation } from 'react-router-dom';

import { MainHeader, MainContent } from "./layouts";

import './assets/scss/main.scss'

const App = () => {
  const location = useLocation();
  return (
    <>
      {
        location.pathname === '/' && <MainHeader  />
      }
      <MainContent />
    </>
  );
}

export {App};
