// frontend/src/components/Task/EditTaskPopup/index.vue
<template>
  <Popup v-model:dialog="isOpenEditTask">
    <template v-slot:title> Редактировать задачу </template>
    <template v-slot:content>
      <ContentPopup v-bind:newTask="task" @update:newTask="task = $event" />
    </template>
    <template v-slot:actions>
      <Button :type="'text'" @click="closePopup">ОТМЕНА</Button>
      <Button @click="saveTask" v-if="task && task.author_id === user">СОХРАНИТЬ</Button>
    </template>
  </Popup>
</template>

<script>
import { mapState, mapMutations } from "vuex";
import { apiService } from "../../../shared/api/swagger/swagger";

import ContentPopup from "../ContentPopup";
import { Popup, Button } from "@/components/UI";

export default {
  name: "EditTaskPopup",
  props: ["taskId", "tasks", "user"],
  emits: ["update:taskId"],
  components: {
    ContentPopup,
    Popup,
    Button,
  },
  data() {
    return {
      task: null,
      id: null,
    };
  },
  computed: {
    ...mapState({
      isOpenEditTask: (state) => state.tasks.isOpenEditTask,
    }),
  },
  watch: {
    taskId(value) {
      this.id = value;
    },
    id(value) {
      if (value)
        apiService.tasks.GetById(value).then((res) => {
          this.task = res.data;
        });
    },
  },
  methods: {
    ...mapMutations({
      setOpenEditTask: "tasks/SET_IS_OPEN_EDIT_TASK",
    }),
    closePopup() {
      this.setOpenEditTask(false);
    },
    saveTask() {
      apiService.tasks
        .Update(this.task.id, {
          status_id: this.task.status_id,
          description: this.task.description,
          title: this.task.title,
        })
        .then(() => {
          apiService.tasks
            .Get()
            .then((res) => {
              this.$emit("update:tasks", res.data);
            })
            .then(() => {
              this.closePopup();
            });
        });
    },
  },
  mounted() {
    this.id = this.taskId;
  },
};
</script>

<style lang="scss" scoped></style>

// frontend-react/src/components/Task/EditTaskPopup/index.jsx
import React, { useState, useEffect } from "react";

import { apiService } from "../../../shared/api/swagger/swagger";

import { Popup, Button, ContentPopup } from '../../../components';

const EditTaskPopup = ({ isDialog, show, user, updateTasks }) => {
  const [task, setTask] = useState({
    status_id: -1,
    title: "",
    description: "",
  });

  const closePopup = () => {
    show(false);
  };

  const updateTask = (task) => {
    setTask(task);
  };

  const saveTask = () => {
    apiService.tasks
      .Update(task.id, {
        status_id: task.status_id,
        description: task.description,
        title: task.title,
      })
      .then(() => {
        apiService.tasks
          .Get()
          .then((res) => {
            updateTasks(res.data);
          })
          .then(() => {
            closePopup();
          });
      });
  };

  const titleElement = () => {
    return (
      <>редактировать задачу</>
    )
  };

  const contentElement = () => {
    return (
      <>
        <div>
          <ContentPopup newTask={task} updateTask={(value) => updateTask({...task, ...value})} />
        </div>
      </>
    )
  };

  const actionsElement = () => {
    return (
      <>
        <Button onClick={closePopup} type={'text'}>ОТМЕНА</Button>
        {task && task.author_id === user &&
          <Button onClick={saveTask}>СОХРАНИТЬ</Button>
        }
      </>
    )
  };

  useEffect(() => { 
    apiService.tasks.GetById(isDialog).then((res) => {
      updateTask(res.data);
    });
  }, []);

  return (
    <Popup
      isOpen={isDialog}
      title={titleElement()}
      content={contentElement()}
      actions={actionsElement()}
    />
  )
}

export { EditTaskPopup }
