// frontend/src/pages/AuthPage/index.vue
<template>
  <div class="auth-page">
    <div class="auth-page_form">
      <div class="auth-page_form__header">
        <img
          class="auth-page_form__header icon"
          src="@/assets/images/mountain.png"
          alt="Icon ToDo App"
        />
        <div class="header">
          <h1 class="auth-page_form__header text">
            {{ isSignUp ? "Регистрация" : "Вход" }}
          </h1>
        </div>

        <p :class="['auth-page_form__header', { message: mess }, { error: err }]">
          {{ mess ? mess : err }}
        </p>
      </div>
      <FormAuth v-model:user="user" @update:user="user = $event" />
      <div class="auth-page_form__actions">
        <Button @click="submit" :disabled="isDisabled">{{
          isSignUp ? "ЗАРЕГИСТРИРОВАТЬСЯ" : "ВОЙТИ"
        }}</Button>
        <Button v-if="!isSignUp" :type="'text'" @click="toSignUpForm">
          Зарегистрироваться
        </Button>
      </div>
    </div>
  </div>
</template>

<script>
import { Button } from "@/components/UI";
import FormAuth from "@/components/FormAuth";

import { apiService } from "../../shared/api/swagger/swagger.js";

export default {
  name: "AuthPage",
  components: {
    FormAuth,
    Button,
  },
  data() {
    return {
      isSignUp: false,
      isLoading: false,
      mess: null,
      err: null,
      user: {
        login: null,
        password: null,
      },
    };
  },
  computed: {
    isDisabled() {
      return (!this.user.login || !this.user.password) && !this.isLoading;
    },
  },
  methods: {
    toSignUpForm() {
      this.isSignUp = true;

      this.user = {
        login: null,
        password: null,
      };
    },
    submit() {
      return this.isSignUp ? this.signUp() : this.logIn();
    },
    signUp() {
      this.isLoading = true;
      console.log(this.user);
      apiService.users
        .Create({ ...this.user })
        .then(() => {
          this.mess = "вы успешно зарегистрировались!";
          setTimeout(() => {
            this.$router.push({ name: "ToDo App" });
            this.isLoading = false;
            this.mess = null;
          }, 1000);
        })
        .catch(() => {
          this.err = "ошибка!!";

          setTimeout(() => {
            this.user = {
              login: null,
              password: null,
            };

            this.err = null;
          });
        }, 1000);
    },
    logIn() {
      this.isLoading = true;

      apiService.login
        .Login(this.user)
        .then(() => {
          setTimeout(() => {
            this.$router.push({ name: "ToDo App" });
            this.isLoading = false;
            this.mess = null;
          }, 1000);
        })
        .catch((err) => {
          this.err = err.message;

          setTimeout(() => {
            this.user = {
              login: null,
              password: null,
            };

            this.err = null;
          }, 2000);
        });
    },
  },
  mounted() {
    this.isSignUp = false;
  },
};
</script>

<style lang="scss" scoped></style>

// frontend-react/src/pages/AuthPage/index.jsx
import React, { useState } from "react";
import { useNavigate } from 'react-router-dom';

import { apiService } from '../../shared/api/swagger/swagger.js';

import { Button, FormAuth } from "../../components";

import mountainPng from '../../assets/images/mountain.png';

const AuthPage = () => {
  const navigate = useNavigate()

  let [mess, setMess] = useState("");
  let [err, setErr] = useState("");
  let [user, setUser] = useState({ login: "", password: "" });
  let [isDisabled, setDisabled] = useState(true);
  let [isLoading, setLoading] = useState(false);
  let [isSignUp, setSignUp] = useState(false);

  const updateUser = (newUser) => {
    if(newUser.login && newUser.password){
      setDisabled(false);
    }
    setUser(newUser);
  }

  const toSignUpForm = () => {
    setSignUp(true);

    setUser({
      login: "",
      password: "",
    });
  }

  const signUp = () => {
    setLoading(true);

    apiService.users
      .Create({ ...user })
      .then((res) => {
        localStorage.setItem('user', JSON.stringify(res.data))
        setMess("вы успешно зарегистрировались!");
        setTimeout(() => {
          navigate('/');
          setLoading(false);
          setMess("");
        }, 1000);
      })
      .catch(() => {
        setErr("ошибка!!");

        setTimeout(() => {
          setUser({
            login: "",
            password: "",
          });

          setErr("");
        });
      }, 1000);
  }

  const logIn = () => {
    setLoading(true);
    apiService.login
      .Login(user)
      .then((res) => {
        localStorage.setItem('user', JSON.stringify(res.data));
        setTimeout(() => {
          navigate('/');
          setLoading(false);
          setMess("");
        }, 1000);
      })
      .catch((err) => {
        setErr(err.message)

        setTimeout(() => {
          setUser({
            login: "",
            password: "",
          });

          setErr("");
        }, 2000);
      });
  }


  const submit = () => isSignUp ? signUp() : logIn();

  return (
    <div className="auth-page">
      <div className="auth-page_form">
        <div className="auth-page_form__header">
          <img
            className="auth-page_form__header icon"
            src={mountainPng}
            alt="Icon ToDo App"
          />
          <div className="header">
            <h1 className="auth-page_form__header text">
              { isSignUp ? "Регистрация" : "Вход" }
            </h1>
          </div>

          <p className={`auth-page_form__header ${  mess ? 'message' : '' } ${  err ? 'error' : '' }`}>
            { mess ? mess : err }
          </p>
        </div>
        <FormAuth user={user} update={(value) => updateUser({...user, ...value})}/>
        <div className="auth-page_form__actions">
          <Button onClick={submit} disabled={isDisabled}>{
            isSignUp ? "ЗАРЕГИСТРИРОВАТЬСЯ" : "ВОЙТИ"
          }</Button>
          {!isSignUp &&
            <Button type={'text'} onClick={toSignUpForm}>
              Зарегистрироваться
            </Button>
          }
        </div>
    </div>
  </div>
  )
}

export { AuthPage }
